### ISSUE TITLE
Case-sensitive filenames in `blocks/`

### ISSUE THREAD

**Issue by jeffwheeler** [gseim/gseim#7]
I am seeing issues because Mac's file system is case insensitive, but these filenames are exactly the same except for case. The contents of the files are _not_ identical.

* `blocks/connector_f_2A.block.yml` and `blocks/connector_f_2a.block.yml`
* `blocks/connector_f_2B.block.yml` and `blocks/connector_f_2b.block.yml`

This confuses `git` massively. 😅 

I'd like to fix this, but it's not obvious what the correct fix is. How would you like this handled?

**Comment by gseim** [comment]
I can fix it by changing 2A to 2x and 2B to 2y. Will need to make changes in the existing .grc files and in the documentation as well, but certainly possible. Any better ideas?

**Comment by jeffwheeler** [comment]
That works for me, I've just created pull request #8 to implement that.
