### ISSUE TITLE
Suggest to use standard Python module packaging

### ISSUE THREAD

**Issue by jeffwheeler** [gseim/gseim#9]
Hi Mahesh,

As I mentioned in #6, I've tried to organize GSEIM into a Python multi-package distribution. You can see my first draft of this reorganization in [this branch](https://github.com/jeffwheeler/gseim/tree/custom_gseim_location).

The critical change is to move Python code into `gseim_grc/src/` and to add a [`pyproject.toml`](https://github.com/jeffwheeler/gseim/blob/custom_gseim_location/gseim_grc/pyproject.toml) package configuration file. Each folder there is a _Python package_. This has two big advantages:

1. We can specify dependencies and Python tooling can automatically take care of installing them.
2. Python tooling can install executables in the user's path, so users can simply run `gseim` anywhere, instead of referencing the full path to the `run_gseim` script. It makes for a nicer user experience. 🙂 It is progress towards removing the unfortunate dependency on the source code location.

The [`pyproject.toml`](https://github.com/jeffwheeler/gseim/blob/custom_gseim_location/gseim_grc/pyproject.toml) is the project definition. You'll see that I've defined the project name, version, dependencies (can add version numbers), as well as scripts. Now, it'll be possible to simply run `gseim` or `gseim_plot` directly (`gseim1` and `gseim_parse_filters` too, which used to be scripts in the `exec` folder). This is all handled by `pip` and `setuptools`.

To use this branch, you'll need to navigate into `gseim_grc`, then `pip3 install .` (that installs the packages in the current directory). After that, you'll be able to `import` the Python modules just like you would normally, any time you run Python (e.g. launch `python3` then try `from gseim import parse_filters`). You'll need to copy `libfilter.so` to `gseim_grc/src/gseim/` instead of the original `exec` folder, too. (I'd like to have this happen automatically?)

_(Note that during development, it's useful to install packages in [development mode](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#development-mode). Replace the above installation command with `pip3 install --editable .`. Then, changes you make to the Python code will be reflected without having to install the package again.)_

I've also reworked the preprocessor slightly in this branch. Notice in [`gseim_preproc.py`](https://github.com/jeffwheeler/gseim/blob/custom_gseim_location/gseim_grc/gseim/exec/gseim_preproc.py), I import your utilities file from the Python module (`import gseim.gutils_gseim as gu`), as is typical in Python, and we didn't need any `PYTHONPATH` manipulation. This is possible due to the above code. This does mean that you'll need to install the Python package prior to running the preprocessor, so that the preprocessor can import the relevant module code.

---

I've also moved the element library `ebe`, `xbe`, and `bbe` folders into the Python distribution so they will be installed as part of the package. This allows Python code to directly query the location of these files instead of hard-coding a location. This is useful because it removes the dependency on where the user has downloaded GSEIM. (It also means you could distribute GSEIM as a package without the user downloading and building the source.) For me, they are installed as part of the package into the following directory, but this will vary with install:

```
>>> from importlib_resources import files
>>> files('gseim.data').joinpath('xbe')
PosixPath('/Users/jeff/Desktop/gseim/gseim_venv/lib/python3.9/site-packages/gseim/data/xbe')
```

After this change, the only dependency on the user's source code download location is in [`solveblocks.cpp`](https://github.com/jeffwheeler/gseim/blob/custom_gseim_location/gseim_grc/gseim/cppsrc/solveblocks.cpp#L800) (line 800). In the current version of the concept, the library directory gets build into the `gsmain` binary as part of the `mkgseim`. (That Makefile uses a script [`cpp_builder_helpers.py`](https://github.com/jeffwheeler/gseim/blob/custom_gseim_location/gseim_grc/src/gseim/cpp_builder_helpers.py) to query and embed the library location.

Let me know what you think, and I can continue tuning it as you like.

_(One more note: This doesn't include the fixes for Matplotlib 3.1.2 from #6, so you'll probably have trouble running `gseim_plot` if you test out this branch.)_

**Comment by gseim** [comment]
> As I mentioned in #6, I've tried to organize GSEIM into a Python multi-package distribution. You can see my first draft of this reorganization in ...

It will be great to have this reorganization. 

> 1. We can specify dependencies and Python tooling can automatically take care of installing them.
> 2. Python tooling can install executables in the user's path, so users can simply run `gseim` anywhere, instead of referencing the full path to the `run_gseim` script. It makes for a nicer user experience

That will be perfect. I know that this is how most packages are designed, but did not know how to do that. Thanks.
Something to keep in mind: the C++ engine generates output files in a fixed directory (with respect to the home directory) and gseim_plot.py takes those from there.

> I've also moved the element library `ebe`, `xbe`, and `bbe` folders into the Python distribution so they will be installed as part of the package.

This is useful. We will need to make some changes in the C++ code since it shares the .ebe and .xbe files with the python code. GSEIM allows the user to add new .xbe and .ebe files. In that case, a recompilation of the C++ part is required. (Also, the user will need to edit blocks.tree.yml, and create the corresponding .block.yml file). Something to keep in mind...

Since my last commit on 2022-06-20, I have made several changes, including bug-fixes. Also, I added a "reload" feature in gseim_plot.py to load the same file again without using the file selector. I will commit these changes later today. Please use that version. I do not expect to make any major changes after that except adding more project files (.grc files).

Mahesh

**Comment by jeffwheeler** [comment]
> It will be great to have this reorganization.

Glad to hear it.

> Something to keep in mind: the C++ engine generates output files in a fixed directory (with respect to the home directory) and gseim_plot.py takes those from there.

> This is useful. We will need to make some changes in the C++ code since it shares the .ebe and .xbe files with the python code. GSEIM allows the user to add new .xbe and .ebe files. In that case, a recompilation of the C++ part is required. (Also, the user will need to edit blocks.tree.yml, and create the corresponding .block.yml file). Something to keep in mind...

Ah, yes, I noticed this. (Also, you've written _awesome_ [documentation](https://gseim.github.io/build/html/organisation.html) to explain it that really got me excited about this project.)

I need to think more about the best way to handle this. One thought I've had is that it would be useful to distinguish the _library_ `.ebe`/`.xbe`/etc. files and the user's. A lot of similar software (e.g. LTSpice) separates the two. If the user edits the library's `.ebe`/.`xbe`/etc. files without creating a pull request, it'll cause a conflict when the package author updates those files and the user pulls the latest version. So, it might be better if we provide a location for users to write their own libraries if they don't want to submit their changes back to the package.

Would you be willing to accept a patch that separates the user and package libraries like that?

If so, the next step would be to figure out how to handle the dynamic compilation of the user library. I wonder if we can depend on some Python libraries that provide an interface to `g++` (or I would prefer `clang`) to build the user library into libraries that we dynamically load in the solver. It seems possible?

> Since my last commit on 2022-06-20, I have made several changes, including bug-fixes. Also, I added a "reload" feature in gseim_plot.py to load the same file again without using the file selector. I will commit these changes later today. Please use that version. I do not expect to make any major changes after that except adding more project files (.grc files).

Sure, I can rebase onto that commit once you share it. 🙂

It looks like the `.grc` files might make a useful test suite. If you're interested, it's possible to setup [Continuous Integration](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python) on GitHub, so that every commit or pull request is tested against a test suite to confirm it doesn't break anything.

**Comment by gseim** [comment]
Jeff, I was wondering if the following could be made read-only for the user:
1. gseim_grc/gseim/exec/gseim_slvparms.in and gseim_grc/gseim/exec/slvparms.in: these contain solve block default parameter values.
2. xbe/ebe/bbe from the library: (as you have already mentioned)
3. gseim_grc/subckt_grc/s_xxx.grc and gseim_grc/subckt/s_xxx.hblock.yml: these are sub-circuits (hierarchical blocks) which come with the distribution. I am not sure whether it would be good to allow them to be changed by the user or not. In a way, they may also be considered to be library blocks.

Mahesh

**Comment by jeffwheeler** [comment]
Hi Mahesh,

I don't have a solution yet, but I wanted to let you know I've been playing around with this in [this branch](https://github.com/jeffwheeler/gseim/tree/update_build_system). It is _very much_ a work in progress and almost certainly won't run on your system. It's just some random ideas I've been experimenting with.

I have been playing around with using [Bazel](https://bazel.build) (it's Google's widely-used build system) and have setup a few different tests ([1](https://github.com/jeffwheeler/gseim/blob/update_build_system/gseim_grc/src/gseim/gseim_parser_test.py), [2](https://github.com/jeffwheeler/gseim/blob/update_build_system/gseim_grc/src/gseim_cpp_lib/gseim_solver_test.py), [3](https://github.com/jeffwheeler/gseim/blob/update_build_system/gseim_grc/src/gseim_plot/plot_test.py)), so I can now do this:
```
src ᐅ bazel test //... --cxxopt=-std=c++17
INFO: Analyzed 12 targets (0 packages loaded, 0 targets configured).
INFO: Found 9 targets and 3 test targets...
INFO: Elapsed time: 2.542s, Critical Path: 2.43s
INFO: 4 processes: 6 darwin-sandbox.
INFO: Build completed successfully, 4 total actions
//gseim:gseim_parser_test                                                PASSED in 0.7s
//gseim_cpp_lib:gseim_solver_test                                        PASSED in 1.5s
//gseim_plot:plot_test                                                   PASSED in 1.6s

Executed 3 out of 3 tests: 3 tests pass.
INFO: Build completed successfully, 4 total actions
```
... which builds everything and then tests the parser and simulator, plus the plotting GUI.

> Jeff, I was wondering if the following could be made read-only for the user:

I don't think we can make files read-only (since as the tool is currently designed, the user must have permissions to write the files), but we can design a system where the tool doesn't write back into the source directory. This is generally good practice (actually, Bazel enforces this) since it enforces that the code can be reliably produced from the git tree. One approach I've been thinking about is generating a shared object file for each `xbe`/`ebe` file and dynamically loading it (e.g. with [`dlopen`](https://linux.die.net/man/3/dlopen), but this is just an idea and I haven't proven this out.

**Comment by gseim** [comment]
> I have been playing around with using [Bazel](https://bazel.build) (it's Google's widely-used build system) and have setup a few different tests ([1]
> ... which builds everything and then tests the parser and simulator, plus the plotting GUI.

Great. I was not familiar with Bazel, but it looks like a very good option.

> the files), but we can design a system where the tool doesn't write back into the source directory. This is generally good practice (actually, Bazel enforces this) since it enforces that the code can be reliably produced from the git tree.

Yes, good idea.
